### ISSUE TITLE
Error when running npm run db:generate

### ISSUE THREAD

**Issue by steph-koopmanschap** [steph-koopmanschap/jasma#21]
In /express/ dir
When running the command
`npm run db:generate 100` 
Running the command `npm run db:resetTables` before `db:generate` has a higher chance of the error occurring.

There occurs an error. (see error below). 
This error does not happen all the time, only occasionally.
The error does not affect the entire app. And it does not affect the entire generation process.
It only affects less followers being generated.

The error occurs in the code in:
`/express/models/UserFollowing.js` 
in the ` static async generate(n)` function.

UPDATE:
 This error probably happens because the same combination of user_id and follow_id is being generated.
 The current code only prevents the same user_id and follow_id from being generated in a single entry.
 But not duplicate entries.

```
          follow_id: '09d01dfd-e696-4b40-aef7-af03d7e8d6ac'
        },
        _previousDataValues: { user_id: undefined, follow_id: undefined },
        uniqno: 1,
        _changed: Set(2) { 'user_id', 'follow_id' },
        _options: {
          isNewRecord: true,
          _schema: null,
          _schemaDelimiter: '',
          attributes: undefined,
          include: undefined,
          raw: undefined,
          silent: undefined
        },
        isNewRecord: true
      },
      validatorKey: 'not_unique',
      validatorName: null,
      validatorArgs: []
    },
    ValidationErrorItem {
      message: 'follow_id must be unique',
      type: 'unique violation',
      path: 'follow_id',
      value: '09d01dfd-e696-4b40-aef7-af03d7e8d6ac',
      origin: 'DB',
      instance: UserFollowing {
        dataValues: {
          user_id: '79d86b47-acd1-4752-aeb1-81826ebe3549',
          follow_id: '09d01dfd-e696-4b40-aef7-af03d7e8d6ac'
        },
        _previousDataValues: { user_id: undefined, follow_id: undefined },
        uniqno: 1,
        _changed: Set(2) { 'user_id', 'follow_id' },
        _options: {
          isNewRecord: true,
          _schema: null,
          _schemaDelimiter: '',
          attributes: undefined,
          include: undefined,
          raw: undefined,
          silent: undefined
        },
        isNewRecord: true
      },
      validatorKey: 'not_unique',
      validatorName: null,
      validatorArgs: []
    }
  ],
  parent: error: duplicate key value violates unique constraint "users_following_pkey"
      at Parser.parseErrorMessage (/home/notaspoon/programming/collab/jasma/express/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/home/notaspoon/programming/collab/jasma/express/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/home/notaspoon/programming/collab/jasma/express/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/home/notaspoon/programming/collab/jasma/express/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 299,
    severity: 'ERROR',
    code: '23505',
    detail: 'Key (user_id, follow_id)=(79d86b47-acd1-4752-aeb1-81826ebe3549, 09d01dfd-e696-4b40-aef7-af03d7e8d6ac) already exists.',
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: 'public',
    table: 'users_following',
    column: undefined,
    dataType: undefined,
    constraint: 'users_following_pkey',
    file: 'nbtinsert.c',
    line: '663',
    routine: '_bt_check_unique',
    sql: 'INSERT INTO "users_following" ("user_id","follow_id") VALUES ($1,$2) RETURNING "user_id","follow_id";',
    parameters: [
      '79d86b47-acd1-4752-aeb1-81826ebe3549',
      '09d01dfd-e696-4b40-aef7-af03d7e8d6ac'
    ]
  },
  original: error: duplicate key value violates unique constraint "users_following_pkey"
      at Parser.parseErrorMessage (/home/notaspoon/programming/collab/jasma/express/node_modules/pg-protocol/dist/parser.js:287:98)
      at Parser.handlePacket (/home/notaspoon/programming/collab/jasma/express/node_modules/pg-protocol/dist/parser.js:126:29)
      at Parser.parse (/home/notaspoon/programming/collab/jasma/express/node_modules/pg-protocol/dist/parser.js:39:38)
      at Socket.<anonymous> (/home/notaspoon/programming/collab/jasma/express/node_modules/pg-protocol/dist/index.js:11:42)
      at Socket.emit (node:events:513:28)
      at addChunk (node:internal/streams/readable:324:12)
      at readableAddChunk (node:internal/streams/readable:297:9)
      at Readable.push (node:internal/streams/readable:234:10)
      at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {
    length: 299,
    severity: 'ERROR',
    code: '23505',
    detail: 'Key (user_id, follow_id)=(79d86b47-acd1-4752-aeb1-81826ebe3549, 09d01dfd-e696-4b40-aef7-af03d7e8d6ac) already exists.',
    hint: undefined,
    position: undefined,
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: 'public',
    table: 'users_following',
    column: undefined,
    dataType: undefined,
    constraint: 'users_following_pkey',
    file: 'nbtinsert.c',
    line: '663',
    routine: '_bt_check_unique',
    sql: 'INSERT INTO "users_following" ("user_id","follow_id") VALUES ($1,$2) RETURNING "user_id","follow_id";',
    parameters: [
      '79d86b47-acd1-4752-aeb1-81826ebe3549',
      '09d01dfd-e696-4b40-aef7-af03d7e8d6ac'
    ]
  },
  fields: {
    user_id: '79d86b47-acd1-4752-aeb1-81826ebe3549',
    follow_id: '09d01dfd-e696-4b40-aef7-af03d7e8d6ac'
  },
  sql: 'INSERT INTO "users_following" ("user_id","follow_id") VALUES ($1,$2) RETURNING "user_id","follow_id";'
}

Node.js v18.7.0
```

**Comment by steph-koopmanschap** [comment]
Fixed in django port https://github.com/steph-koopmanschap/jasma/commit/a75cbec7638a89bd75450d9c3fbd81b86cbb09a0
